name: Sync
authors:
  - Kyro
  - Wiji
version: 1.0.0
main: net.pitsim.sync.PitSim
description: Sync Pit Gamemode
depend:
  - Citizens
  - Vault
  - PlaceholderAPI
  - NoteBlockAPI
  - ProtocolLib
  - Essentials
commands:
  pitsim:
  ps:
  oof:
  atest:
  enchant:
  fresh:
  show:
  perks:
  jewel:
  market:
  enchants:
  setkills:
  togglestereo:
  donator:
  renown:
  bounty:
  spawn:
  changemap:
  crategive:
  cg:
  afk:
  setvalue:
  check:
  ecitems:
  shop:
  store:
  discord:
  disc:
  resource:
  lightning:
  duel:
  captcha:
  stash:
  unstash:
  void:
  hopper:
  spawn:
  sync: